
project_id = "aqncxoewceqjaodhaavy"

[storage.buckets.avatars]
public = true
file_size_limit = "5MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp"]

[storage.buckets.trip-covers]
public = true
file_size_limit = "5MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp"]
